version: '3.8'
services:
  mysql-films:
    image: samuelgarciahub/tfg-mysql-films #nombre de la imagen que hemos creado
    restart: always
    container_name: mysql-films
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: films
      MYSQL_TCP_PORT: 3306
  phpmyadmin-films:
    depends_on:
      - mysql-films
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-1
    ports:
      - '8084:80'
    environment:
      PMA_HOST: mysql-films    
  mysql-series:
    image: samuelgarciahub/tfg-mysql-series #nombre de la imagen que hemos creado
    restart: always
    container_name: mysql-series
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    ports:
      - '3307:3307'
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: series 
      MYSQL_TCP_PORT: 3307
  phpmyadmin-series:
    depends_on:
      - mysql-series
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-2
    ports:
      - '8081:80'
    environment:
      PMA_HOST: mysql-series    
  mysql-reviews:
    image: samuelgarciahub/tfg-mysql-reviews #nombre de la imagen que hemos creado
    restart: always
    container_name: mysql-reviews
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE 
    ports:
      - '3308:3308'
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: reviews
      MYSQL_TCP_PORT: 3308
  phpmyadmin-reviews:
    depends_on:
      - mysql-reviews
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-3
    ports:
      - '8082:80'
    environment:
      PMA_HOST: mysql-reviews      